--- # this is ignore_errors file
- hosts: devops
  user: ansible
  become: yes
  connection: ssh

  tasks:
    - name: install httpd
      yum: name=httpd state=present
    - name: copy  index file
      copy: src=index.htl dest=/var/www/html
      ignore_errors: yes
    - name: start httpd
      service: name=httpd state=started

