--- # third variable method
- hosts: devops
  user: ansible
  become: yes
  connection: ssh

  vars_prompt:
    - name: pkg
      prompt: enter package name
      private: no

  tasks:
    - name: install httpd
      yum: name={{pkg}} state=present
    - name: copy index.html file
      copy: src=index.html dest=/var/www/html
    - name: start httpd
      service: name={{pkg}} state=started 

